- hosts: all
vars_files: vars.yml
tasks:
  - name: Ajout nouvel utilisateur
    user:
      name=provision
      password={{provision_password}}
  - name: Ajout de l'utilisateru dans les sudoers
    copy:
      dest: "etc/sudoers.d/provision"
      content: "provision ALL=(ALL:ALL) NOPASSWD:ALL"
  - name: Deployment SSH Key
    authorized_key: user=provision
                    key="{{ lookup('file', '/home/provision/.ssh/id_rsa.pub') }}"
                    state=present
  - name: Disable Password Authenthication
    lineinfile:
      dest=/etc/ssh/sshd_config
      regexp='^PasswordAuthentication'
      line="PasswordAuthentication no"
      state=present
      backup=yes
    notify:
      - restart ssh
  - name: Disable Root Login
     lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PermitRootLogin'
           line="PermitRootLogin no"
           state=present
           backup=yes
     notify:
       - restart ssh
 
   handlers:
   - name: restart ssh
     service:
       name=sshd
       state=restarted
